project_name: go-gallery

before:
  hooks:
    - go mod download

builds:
  - id: go-gallery
    main: ./gallery.go
    binary: go-gallery
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "creekorful/go-gallery:latest"
      - "creekorful/go-gallery:{{ replace .Tag \"v\" \"\" }}"
      - "creekorful/go-gallery:{{ .Major }}"
    skip_push: false

brews:
  - name: go-gallery
    tap:
      owner: creekorful
      name: homebrew-packages
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/creekorful/go-gallery/releases/download/{{ .Tag }}/{{ replace .ArtifactName \"v\" \"\" }}"
    download_strategy: CurlDownloadStrategy
    folder: Formula
    homepage: "https://github.com/creekorful/go-gallery"
    description: "Generate a photography portfolio website for your photos"
    license: "GPL-3.0-only"
    test: |
      system "#{bin}/go-gallery -h"
    install: |
      bin.install "go-gallery"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"

release:
  prerelease: true