project_name: go-gallery

before:
  hooks:
    - go mod download

builds:
  - id: go-gallery
    main: ./gallery.go
    binary: go-gallery
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "creekorful/go-gallery:latest"
      - "creekorful/go-gallery:{{ replace .Tag \"v\" \"\" }}"
      - "creekorful/go-gallery:{{ .Major }}"
    skip_push: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"

release:
  prerelease: true